// <auto-generated />
using System;
using MagicVilla_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupants")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 1, 7, 19, 53, 55, 334, DateTimeKind.Local).AddTicks(7022),
                            DateUpdated = new DateTime(2024, 1, 7, 19, 53, 55, 334, DateTimeKind.Local).AddTicks(7035),
                            Description = "Detail of the villa...",
                            ImagenUrl = "",
                            Name = "Villa Real",
                            Occupants = 5,
                            Rate = 200.0,
                            Services = "",
                            SquareMeters = 50
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 1, 7, 19, 53, 55, 334, DateTimeKind.Local).AddTicks(7037),
                            DateUpdated = new DateTime(2024, 1, 7, 19, 53, 55, 334, DateTimeKind.Local).AddTicks(7037),
                            Description = "Detail of the villa...",
                            ImagenUrl = "",
                            Name = "Premium beach view",
                            Occupants = 4,
                            Rate = 150.0,
                            Services = "",
                            SquareMeters = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
